### ISSUE TITLE
Part of website fixes

### ISSUE THREAD

**Issue by pawelkisielewicz** [Code-Poets/project-liberation#103]
Part of https://github.com/Code-Poets/project-liberation/issues/82 fixes

1. Margin bottom is to big on mobile screen.

![Screenshot_2019-11-04-11-46-32-823_com android chrome](https://user-images.githubusercontent.com/47628251/68120197-ffea2d80-ff04-11e9-89f5-7038db8d42f9.png)
<br>
2. Z-index on text div should be bigger than next hotspot z-index and menu z-index.
![smaller_screen](https://user-images.githubusercontent.com/47628251/68120199-0082c400-ff05-11e9-83e3-ffca725d1bbe.png)
<br>
3. One of element has incorrect styles on smaller screen.
![wrong_display](https://user-images.githubusercontent.com/47628251/68120201-0082c400-ff05-11e9-9988-352d25559f07.png)

**Comment by kbeker** [comment]
@pawelkisielewicz please be more precises about issue name :) 

> 1. Margin bottom is to big on mobile screen.

On which page/subpage?

> 2. Z-index on text div should be bigger than next hotspot z-index and menu z-index.

On text which is where?

> 3. One of element has incorrect styles on smaller screen.

What element? :D
