### ISSUE TITLE
Feature add google map navigator

### ISSUE THREAD

**Issue by kbeker** [Code-Poets/project-liberation#14]
Create map_navigator template which should consist google map same as on pdf preview.

You have to generate your own google api key for testing. One for production will be generated by @bartoszbetka and will be stored in secrets.

Please create `GOOGLE_API_KEY` setting which in `base.py` setting file will be set on `None`. Also please add `system_check` for this setting to make sure that anyone who will start server will have correct api key in his settings.

**Comment by kbeker** [comment]
Main Page design: https://github.com/Code-Poets/project-liberation/wiki/Main-Page-design

**Comment by kbeker** [comment]
@maciejSamerdak issue updated.

**Comment by maciejSamerdak** [comment]
Issue resolved with #42.
