### ISSUE TITLE
Feature add estimate project subpage

### ISSUE THREAD

**Issue by kbeker** [Code-Poets/project-liberation#17]
Create database model which will have all necessary fields for estimate project subpage.
Create django form for this subpage.
Example of how it should look is below. There will be one change in this example, but this will be soon updated.

**Comment by kbeker** [comment]
![estimate](https://user-images.githubusercontent.com/26469852/64697153-75ef8c80-d4a0-11e9-913b-c0cd36373f33.jpg)

**Comment by pawelkisielewicz** [comment]
Pola wymagane mają być walidowane po naciśnięciu guzika "estimate project"
- w przypadku źle wypełnionego pola, podświetla się ono na czerwono, dodatkowo pojawia się napis "wymagane pola muszą być uzupełnione"
- ekran scrolluje się do tego pola

Defaultowo guzik "estimate project" jest disabled, a dopiero po zaznaczeniu zgody "I have read and accept Privacy Policy", staje się active

**Comment by pawelkisielewicz** [comment]
Required fields should be validated after pressing button "estimate project"

- if field is incorrect filled, it is marked red and text is shown:
"wymagane pola muszą być uzupełnione"
- screen is scrolling to this field

Button "estimate project" is disabled by default. It is active after select checkbox "I have read and accept Privacy Policy"

**Comment by kbeker** [comment]
@pawelkisielewicz should it really be shown `"wymagane pola muszą być uzupełnione"` or maybe in english?

**Comment by pawelkisielewicz** [comment]
english, right :)
