### ISSUE TITLE
Ready to work with us section is not reponsible on iphone 5S

### ISSUE THREAD

**Issue by Szymiks** [Code-Poets/project-liberation#31]
This section is not responsive on Iphone 5S and due to this my containers are going to be bigger and the for instance main screen template is not on full width and what is more we are able to move screen to ther right for few px. Tomorrow I will attachet some img to explain more.

**Comment by Szymiks** [comment]
![bug](https://user-images.githubusercontent.com/47628251/67071307-7a375580-f182-11e9-9bf8-664ba0636b8f.png)
![bug2](https://user-images.githubusercontent.com/47628251/67071309-7a375580-f182-11e9-8ddb-2383885f1ae5.png)

**Comment by maciejSamerdak** [comment]
I missed this issue, I apologize.

Issue has been fixed with #43
